<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entities\Auditoria\**" />
    <Compile Remove="Entities\Catalogos\**" />
    <Compile Remove="Entities\Citas\**" />
    <EmbeddedResource Remove="Entities\Auditoria\**" />
    <EmbeddedResource Remove="Entities\Catalogos\**" />
    <EmbeddedResource Remove="Entities\Citas\**" />
    <None Remove="Entities\Auditoria\**" />
    <None Remove="Entities\Catalogos\**" />
    <None Remove="Entities\Citas\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entities\Usuarios\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
  </ItemGroup>

</Project>
